### ISSUE TITLE
Когда расширение выйдет на Google Chrome?

### ISSUE THREAD

**Issue by Atashka56** [LordTheWanderer/TSE#1]
Здравствуйте. Я вам уже писал об этом два года назад, когда расширение выйдет на Google Chrome? Выпустите своё расширение пожалуйста на Chrome если в магазине не получается, хотя бы ссылку на .crx файл.

**Comment by LordTheWanderer** [comment]
Я не пользуюсь Google Chrome. Если бы там была бесплатная регистрация для разработчиков расширений, давно бы выпустил.
.crx файл тут добавлю, ок.

**Comment by Atashka56** [comment]
Скажите пожалуйста, когда добавите .crx файл он же будет нормально работать
на хром?

вс, 15 янв. 2023 г. в 20:48, LordTheWanderer ***@***.***>:

**Comment by LordTheWanderer** [comment]
https://github.com/LordTheWanderer/TSE/releases/tag/v0.5.2-chrome-experimental

На Opera работает (не полностью), нужно переделывать под manifest v3, Chrome может v2 не принять. Полноценная версия будет позже...

**Comment by Atashka56** [comment]
Спасибо большое. У меня браузер не Chrome, а на базе него Яндекс браузер,
они надеюсь нескоро обновятся до manifest v3, расширение встало отлично.
Что подразумевается под полноценной версией? сейчас в файле .crx не
полноценная?
Я давний пользователь расширения Torrents MultiSearch, каждый день им
пользуюсь, но белый цвет просто убивает, у меня просто много плавающих
мушек в глазах, на белом фоне их видно, поэтому винду и все сайты с
помощью расширения перевёл на тёмные темы, а так как разработчик  Torrents
MultiSearch забросил своё расширение, нет даже надежды на тёмную тему, да и
с переходом на manifest v3 расширение просто рано или поздно перестанет
работать, в вашем расширении есть тёмная тема, спасибо.

У меня есть ещё несколько вопросов по поводу вашего TSE расширения, если вы
не против я их задам?

**Comment by LordTheWanderer** [comment]
Не работает ПКМ - поиск по выделенному тексту. Ошибки в консоли надо исправлять. Подробно не проверял, только основные функции. Исправлю и будет полноценная версия!
В Яндекс браузере скорее всего нет таких жестких ограничений, как в Хроме.
Да, я тоже пользовался тем расширением, а потом оно на Firefox вообще пропало, поэтому и сделал свое)

Да, задавайте вопросы)

**Comment by Atashka56** [comment]
Я как раз хотел спросить про ПКМ поиск по выделенному тексту)) очень
удобная вещь, жаль что её сейчас нет, буду ждать.
Расширение Torrents MultiSearch тоже пропало из магазина Хром, пришлось
искать .crx файл на сторонних сайтах.

Вопросы)
1. Я так понимаю можно добавить сторонние трекеры? путём нажатия на кнопку
Trackers, но как это сделать? может есть видео инструкция или просто
инструкция? пробовал добавить код трекеров из Torrents MultiSearch не
получается.
2. Можно ли передвигать менять местами трекеры в левом списке? просто я
привык к определённому порядку)
3. Как я могу отслеживать выход новых версий вашего расширения в .crx
формате?

И рекомендации, вещи которые есть в расширении Torrents MultiSearch но нет
к сожалению в вашем расширении:
Это каталог категорий по выдаче, это сколько всего выдач количество,
фильмы, игры, музыка и т.д.
Я обычно сортирую список выдачу по дате, чтоб скачивать новые последние
раздачи, в Torrents MultiSearch написано когда была добавлена раздача
вплоть до часов: 11 часов назад, 3 дня назад, 8 месяцев назад, 4 года
назад, мне кажется так гораздо удобней и информативней чем просто дата.
Русский язык, понимаю что он там не особо нужен, так как не очень много
слов, но из-за этого вроде как и легче это реализовать)
Хотелось бы так же видеть экспорт/импорт, но понимаю что сейчас это не
особо нужно, так как настроек практически нет.

Если можно это реализовать было бы супер, я бы мог привлечь ещё людей к
вашему расширению, у нас даже была группу любителей Torrents MultiSearch,
делились друг с другом кодами на разные трекеры, такое расширение как TSE
жизненно необходима сообществу)
Заранее спасибо за ответы.

**Comment by LordTheWanderer** [comment]
1. Да, это пока простейший вариант, нужно будет привести к более приятному виду.
Вот пример: https://github.com/LordTheWanderer/TSE/blob/main/trackers.js

"trackerName": название трекера
"trackerActive": активен ли трекер по умолчанию в левом меню TSE
"trackerDescription": описание трекера
"trackerIcon": иконка трекера в формате base64
"trackerURL": ссылка на трекер
"searchURL": ссылка на поиск на трекере
"searchURLTopSeeds": ссылка на поиск на трекере с сортировкой по количеству сидов
"method": способ GET или POST
"windows1251": кодировка страницы windows1251 или нет
"authReq": требуется ли регистрация для поиска на трекере
"authURL": ссылка на страницу с логином
"auth": селектор для определения того, что сайт требует регистрацию
"selector": селектор таблицы результатов
"skipFromStart": пропуск первого результата в таблице (например, шапки)
"title": селектор названия результата
"date": селектор даты результата
"dateType": тип даты результата
    ["byte"]: byte = 70152431104
    ["eng"]: english = 2020-08-09 03:40:32
    ["rusShort"]: russian = 08 Июн 21 or 17/04/20 or 17.04.20
    ["rusFull"]: russian = 30 октября 2019 в 19:29:32
    ["rusDots"]: russian = 30.04.2021 в 09:54
    ["rusLines"]: russian = 2020-01-30 18:25:19
    ["byte/rusShort/rusDots", "attr", "data-ts_text"]: тип даты, и дата берется из атрибута data-ts_text
"size": селектор размера результата
"sizeType": тип размера результата
    ["byte", ""]: byte = 1620757868
    ["eng", ""]: english = 4.49 GB
    ["rus", ""]: russian = 4.49 ГБ
    ["byte/eng/rus", "attr", "data-ts_text"]: тип размера, и размер берется из атрибута data-ts_text
"seeds": селектор сидов результата
"peers": селектор пиров результата
"baseURL": начало ссылки на страницу результата
"url": селектор окончания ссылки на страницу результата
"baseDownloadURL": начало ссылки для скачивания торрент-файла
"downloadURL": селектор окончания ссылки на торрент-файл

2. На данный момент они идут в том порядке, как указаны в файле \engine\js\trackers.js
Если очень хочется, можете скачать .crx файл, распаковать, открыть файл trackers.js и изменить порядок. После этого при включенном режиме разработчика на странице расширений браузера нажать кнопку "Упаковать расширение", указать распакованную ранее папку и получить новый .crx файл.

3. Буду выкладывать новые версии здесь на гитхабе в "релизах".

> Это каталог категорий по выдаче, это сколько всего выдач количество, фильмы, игры, музыка и т.д.
На рутрекере и nnmclub категории можно хотя бы комбинировать, но на руторе и кинозале "фильмы" это и "Зарубежные фильмы", и "Наши фильмы", и "Телевизор" и т.д., есть категории, которых нет на других сайтах. В итоге это всё выглядит как каша и переусложнение. А изначально это расширение задумывалось как простое и быстрое.

> раздача вплоть до часов
Так и работает (и сортировка учитывает и часы, и минуты), но время не выводится, т.к. оно будет занимать место слева от названия результата, что приведет к снижению читабельности результатов и перегрузке текстом, который не несет особой ценности.

> русский язык, экспорт/импорт
Вы и сами ответили на свой вопрос. Это, возможно в будущем.

> кодами на разные трекеры
Не уверен, что тот формат, в котором сейчас хранятся трекеры, будет конечным (особенно дата и размер)... Это тоже на будущее.

**Comment by Atashka56** [comment]
Если у меня не получится добавить вручную другие трекера, могу я вас
попросить чтоб вы создали код этого трекера и скинули мне? просто я не
силён в создании этих кодов глаза разбегаются, от Torrents MultiSearch у
меня даже есть от разраба старое видео инструкция, но у меня всё равно не
получается) а почему вы просто не скопировали чтоб коды были как в Torrents
MultiSearch? и они были бы взаимозаменяемые, не нужно было бы создавать
коды с нуля.
На самом деле я сам нечасто пользовался этими каталогами категорий по
выдаче, на крайняк можно дописать например lossless и т.д. просто хочется
видеть общее количество раздач которые удалось найти, это очень удобно.
Не нужно добавлять можно ведь просто дату раздач заменить как это
сделано в Torrents
MultiSearch, вот посмотрите пожалуйста на скрин, я там ещё указал где
показывается число найденных раздач. И ваш скрин, плюс пример перевода на
русский язык)

[image: sshot-11.png]  [image: sshot-22.png]


вт, 17 янв. 2023 г. в 05:46, LordTheWanderer ***@***.***>:

**Comment by LordTheWanderer** [comment]
> Если у меня не получится добавить вручную другие трекера, могу я вас попросить чтоб вы создали код этого трекера и скинули мне?

Давайте, возможно даже добавлю в основную версию.

> а почему вы просто не скопировали чтоб коды были как в Torrents MultiSearch? и они были бы взаимозаменяемые, не нужно было бы создавать коды с нуля.

В таком почему бы не использовать, например, коды отсюда:
https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Definitions
Они постоянно обновляются. А тогда почему бы вообще не пользоваться этой программой по ссылке выше?
Я делал расширение TSE для себя (в основном для 3 основных трекеров), добавил возможность добавлять новые трекеры в качестве эксперимента, за год или больше об этом спросили только Вы. Так зачем мне тратить кучу времени на то, чтобы подогнать свое расширение под логику другого, которое больше не существует? Сайт с кодами TMS, насколько я знаю, уже не существует. Многие трекеры тоже. Большинство кодов просто не будет работать.

> просто хочется видеть общее количество раздач которые удалось найти, это очень удобно

Если я правильно понимаю, это о количестве результатов? В левом меню справа от названий трекеров это выводится зеленым текстом.

> скрин

Картинок нет, только их названия. Зайдите на гитхаб, посмотрите.

**Comment by Atashka56** [comment]
> Давайте, возможно даже добавлю в основную версию.

Вот несколько трекеров которыми я пользуюсь и вроде как довольно популярны, добавьте их пожалуйста
http://tapochek.net
http://rustorka.com
https://teamhd.org/
http://filmitorrent.net
https://www.lostfilm.tv
https://tr.anidub.life
https://kat.am
Мне кажется чем больше выбора у пользователя, тем лучше)


Пока вы не написали, я и не знал про расширение Jackett, посмотрел на него, мне он показался перегруженным и самое главное там вроде как нет тёмной темы. Мне ваше расширение почти всем устраивает, я не придирчивый, извините если таким показался.

> Если я правильно понимаю, это о количестве результатов? В левом меню справа от названий трекеров это выводится зеленым текстом.

Не совсем так, количество всех найденных результатов из всех трекеров, посмотрите на скрин пожалуйста

> Картинок нет, только их названия. Зайдите на гитхаб, посмотрите.

Извиняюсь, я переписывался свами через gmail почту, наверное поэтому скрины не отобразились.

![sshot-11](https://user-images.githubusercontent.com/85591171/212942605-703a4eb2-9539-48c1-8f5e-ff73fb87c310.png)
![sshot-22](https://user-images.githubusercontent.com/85591171/212942631-b1bf13e3-a083-430a-a7c9-0abe8ad61509.png)

**Comment by LordTheWanderer** [comment]
> у пользователя

Тут другой случай.

> самое главное там вроде как нет тёмной темы

С помощью userscripts можно менять оформление на любых страницах.

> скрин

Категории, общее количество результатов, формат даты/времени, язык, экспорт/импорт - спорные моменты, но приму к сведению, спасибо.

> несколько трекеров

Спасибо, посмотрю.

**Comment by Atashka56** [comment]
Есть небольшая проблема с вашим расширением, при каждом включении Яндекс браузер отключает ваше расширение TSE - Torrents Search Engine выскакивает окошко предупреждения что расширение установлено не с магазина, приходится отдельно включать, а вот расширение TMS которого тоже давно нет в магазине хром, я тоже ведь установил просто .crx файлом и он никогда на него не ругался, сразу всегда работал, скорее всего дело в том что когда то TMS был в магазине хромиевых браузеров, а ваше расширение никогда. Попробуйте пожалуйста добавить ваше расширение в магазин Оперы или же Майкрософта, они же все совместимы, может там бесплатно можно.


> Без регистрации нет поиска

Да, но и на UnionGang без авторизации поиск не работает, единственное на teamhd.org вроде нужен был инвайт.


> Вообще не торрент трекер

Вроде бы торрент трекер, там раздачи скачиваются через торрент клиент так же как и с других трекеров, просто там одна студия.

> Поиск не работает

Очень странно, у меня на TMS работает

![sshot-10](https://user-images.githubusercontent.com/85591171/213508534-65813eb4-e092-4035-8d24-f56288c4c0d8.png)


> На примере

Попробовал ваш код на https://tr.anidub.com/ поиск работает, но при переходе по ссылке, сайт не открывается, всё время висит в url about:blank

**Comment by LordTheWanderer** [comment]
> Яндекс браузер отключает ваше расширение TSE - Torrents Search Engine

Opera не отключает, значит проблема с Яндекс браузером.

> Попробуйте пожалуйста добавить ваше расширение в магазин Оперы или же Майкрософта, они же все совместимы, может там бесплатно можно.

Не буду.

> UnionGang

Был логин и пароль в открытом доступе. Для других сайтов у меня нет данных для входа.

> Вроде бы торрент трекер

Нет, и в его поиске нет никаких данных, кроме названий сериалов. Если хотите, сами добавьте код.

> на TMS работает

Я говорю про сайт. Да и на этом сайте порно. Если хотите, сами добавьте код.

Благодарю Вас за идеи и трекеры.

**Comment by Atashka56** [comment]
> Opera не отключает, значит проблема с Яндекс браузером.

Но Яндекс браузер не отключает TMS который был так же установлен через .crx файл.

> Не буду.

Почему? ведь если получится добавить в эти магазины, пользователей вашим расширением станет больше и проблемы с отключениями при запуске пропадут.


> Я говорю про сайт. Да и на этом сайте порно.

Странно, как тогда в TMS он работает. Честно говоря, про порно я даже и не знал) Это вроде просто очень популярный зарубежный сайт замена пиратской бухте, может вы тогда для неё сможете сделать код? https://thepiratebay.org

**Comment by hArtKor-89** [comment]
Прошу прощения.
Я бы хотел присоединиться к просьбе добавить tapochek.net, но, как я понял, автору требуется доступ к трекеру? Если я смогу выписать автору инвайт, это повысит шансы на добавление трекера в приложение?
Моих знаний не хватает, чтобы добавить код самостоятельно, увы. :(

**Comment by LordTheWanderer** [comment]
> Я бы хотел присоединиться к просьбе добавить tapochek.net, но, как я понял, автору требуется доступ к трекеру? Если я смогу выписать автору инвайт, это повысит шансы на добавление трекера в расширение? Моих знаний не хватает, чтобы добавить код самостоятельно, увы. :(

Да, у меня нет доступа к этому сайту. Наверное получится добавить его, если смогу там зарегистрироваться.

**Comment by hArtKor-89** [comment]
> Да, у меня нет доступа к этому сайту. Наверное получится добавить его, если смогу там зарегистрироваться.

Я могу в любой момент поделиться инвайтом, только мне нужно знать на какой емейл его выписать.
