### ISSUE TITLE
Рутор в режиме "топ-сида" ищет фразу целиком.

### ISSUE THREAD

**Issue by hArtKor-89** [LordTheWanderer/TSE#2]
У рутора отличаются адреса поиска в обычном режиме и режиме "топ сидер", из-за чего в режиме "топ сидер" поиск идет в режиме целой фразы, а не по всем словам в запросе, это можно исправить, чтобы адреса были одинаковые в части /100/:
        "searchURL": "https://rutor.info/search/0/0/100/0/",
        "searchURLTopSeeds": "http://rutor.info/search/0/0/100/2/",

**Comment by LordTheWanderer** [comment]
Спасибо, будет исправлено
